# Gradient Descent:  Feed Forwarding + Back Propogation

~~~~ 

An Example showing python code for a single layer neural network implementing Gradient Descent Algorithm and explaining feed forwarding and back propogation.

Gradient Descent is an algorithm which minimises a cost/loss function iteratively with a given set of parameters to find set of parameters which will minimise the cost function.

It consists of two process - 
1. Feed Forwarding
2. Back Propogation

- Feed Forwarding is the process of moving forward calculating activation values and producing a 
  final result.

- Back Propogation is applying chain rule iteratively in a backward direction to find the most 
  optimum weight values that can minimise the cost function.




EXAMPLE TAKEN HERE ---

- 4 Input Neurons:
                    X1 (W1,W2,W3)
                    X2 (W4,W5,W6)
                    X3 (W7,W8,W9)
                    X4 (W10,W11,W12)
                    
- 3 Hidden Neurons:
                    N1: (X1.W1 + X2.W4 + X3.W7 + X4.W10)
                    N2: (X1.W2 + X2.W5 + X3.W8 + X4.W11)
                    N3: (X1.W3 + X2.W6 + X3.W9 + X4.W12)

- 1 Output Neuron:
                    O: N1.W13 + N2.W14 + N3.W15



~~~~


In [204]:
import numpy as np
import pandas as pd

In [205]:
X = pd.DataFrame([[0,0,0,1],[0,0,1,1],[0,1,1,1],[1,1,1,1],[0,1,0,1]], columns = ['X1', 'X2', 'X3', 'X4'])
Y = pd.DataFrame([[0],[1],[1],[0],[1]], columns = ['Y'])

### INPUT MATRIX

In [206]:
''' Input Matrix:X;  Features:4;  Total_Observations:n (here, 5) '''
X

X1  X2  X3  X4
0   0   0   0   1
1   0   0   1   1
2   0   1   1   1
3   1   1   1   1
4   0   1   0   1

In [231]:
''' WORK FLOW - 

    First set of input neurons:     2nd Set of Input Neurons:
    Input1 Neuron = 0               Input1 Neuron = 0
    Input2 Neuron = 0               Input2 Neuron = 0 
    Input3 Neuron = 0               Input3 Neuron = 1
    Input4 Neuron = 1               Input4 Neuron = 1

'''

X[0:1]

array([[0, 0, 0, 1]])

### ACTUAL VALUES (ANSWERS)

In [208]:
Y

Y
0  0
1  1
2  1
3  0
4  1

##### Converting Dataframes into Arrays for Dot products and further maths

In [209]:
X = np.array(X)
Y = np.array(Y)

### EPOCHS

In [230]:
# Set number of iterations(Epochs)
epochs = 60000

### WEIGHT MATRIX - W0,W1

In [220]:
# Initialize weights
W0 = np.random.random((4,3))
W1 = np.random.random((3,1))

In [221]:
W0

array([[ 0.97527763,  0.08567679,  0.44735341],
       [ 0.13711901,  0.39753707,  0.14015826],
       [ 0.69410935,  0.43648641,  0.37923077],
       [ 0.58148673,  0.60745446,  0.09625728]])

In [222]:
W1

array([[ 0.18841572],
       [ 0.18038189],
       [ 0.9357893 ]])

In [223]:
# Activation Function = Sigmoid
def activation_function(x, deriv=False):
    
    if(deriv == True):
        sigmoid_derivative = x*(1-x)
        return sigmoid_derivative

    sigmoid = 1/(1+np.exp(-x))
    return sigmoid

In [224]:
X[0]

array([0, 0, 0, 1])

In [225]:
X[0].dot(W0)

array([ 0.58148673,  0.60745446,  0.09625728])

In [226]:
X.dot(W0)

array([[ 0.58148673,  0.60745446,  0.09625728],
       [ 1.27559609,  1.04394087,  0.47548804],
       [ 1.4127151 ,  1.44147793,  0.6156463 ],
       [ 2.38799273,  1.52715472,  1.06299971],
       [ 0.71860575,  1.00499153,  0.23641553]])

In [229]:
for i in range(epochs):
    
    # Feed Forwarding- L0:Input Layer;  L1:Hidden Layer;  L2:Output Layer
    L0 = X
    L1 = activation_function(X.dot(W0))
    L2 = activation_function(L1.dot(W1))
    
    # Error between the actual value and the predicted value
    L2_error = Y - L2
    
    if(i % 10000) == 0:
        print("Error:" + str(np.mean(np.abs(L2_error))))
    
    # Backpropogated: dl/dz*dz/dx = next_error * derivative_of_sigmoid 
    L2_delta = L2_error * activation_function(L2, deriv=True)
    
    # How much did each L1 Value contribute to L2's error
    L1_error = L2_delta.dot(W1.T)
    
    # Backpropogated:  dl/dz*dz/dx = next_error(L1) * derivative_of_sigmoid 
    L1_delta = L1_error * activation_function(L1, deriv=True)
    
    
    # Updating Weights:
    W0 = W0 + L0.T.dot(L1_delta)
    W1 = W1 + L1.T.dot(L2_delta)

Error:0.00121625167325
Error:0.0011781597001
Error:0.00114335891183
Error:0.00111140377325
Error:0.00108192864222
Error:0.00105463027306
Error:0.00102925478188
Error:0.00100558778935


##### - Developed by Pranjal Pathak